#!/usr/bin/env python3
import string
try:
	check = input()
	while True:
		if check[-6:] == 'Error!':
			while check[-6:] == 'Error!':
				file_name = check.split(sep=':')[0]
				# print(file_name + ':\033[91m' + ' Error!' + '\033[0m')
				check = input()
				if 'Unrecognized' in check:
					sp = check.translate(str.maketrans('', '', string.punctuation)).split()
					line = int(sp[3])
					col = int(sp[5][:-3])
					err = 'UNRECOGNIZED_TOKEN'
					desc = 'Unrecognized token'
					print('\033[1m', end='')
					print(file_name, line, col, end='', sep=':')
					print('', '\033[91m' + err + ':' + '\033[0m' + '\033[1m', desc)
					print('\033[0m', end='')
					check = input()
				else:
					while 'line' in check:
						sp = check.translate(str.maketrans('', '', string.punctuation)).split()
						line = int(sp[3])
						col = int(sp[5])
						err = sp[1]
						desc = check.split(sep=':')[-1].strip()
						print('\033[1m', end='')
						print(file_name, line, col, end='', sep=':')
						print('', '\033[91m' + err + ':' + '\033[0m' + '\033[1m', desc)
						print('\033[0m', end='')
						check = input()
		elif check[-3:] == 'OK!':
			file_name = check.split(sep=':')[0]
			print(file_name + ':\033[92m' + ' OK!' + '\033[0m')
			check = input()
		elif 'is not valid C or C header file' in check:
			file_name = check.split()[0]
			# print('\033[1m', end='')
			print(file_name, end=':')
			print(' \033[93mFile Isn\'t valid C or a C Header File')
			print('\033[0m', end='')
			check = input()
		elif check[:25] == 'Missing or invalid header':
			print('\033[93mMissing or invalid header. Header are being reintroduced as a mandatory part of your files. This is not yet an error.')
			print('\033[0m', end='')
			check = input()
		else:
			print('\033[1;95mWARNING: \033[0m\033[1mnorminette string unrecognized by nform:\033[0m', check, )
			check = input()
except EOFError:
	pass